theme = "rust_friendly"

#==================================================================================
[editor]
true-color = true
mouse = true
auto-completion = true
bufferline = "always"
line-number = "relative"
rulers = [120]
auto-format = true
default-yank-register = "+"
auto-info = true
end-of-line-diagnostics = "disable"
scroll-lines = 10
#font = "Fira Code"
#==========================================
[editor.whitespace]
trim-trailing-whitespace = true
#==========================================
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
#==========================================
[editor.indent-guides]
# Affiche les guides d'indentation
render = true
#==========================================
[editor.file-picker]
hidden = false #show hidden files
#==========================================
[editor.gutters]
# Configure les gutters (marges gauches)
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
#==========================================
[editor.inline-diagnostics]
# Active les diagnostics inline (nouveauté)
cursor-line = "warning"    # Montre warnings/errors sur la ligne du curseur
other-lines = "disable"    # Désactive sur les autres lignes
prefix-len = 1
max-wrap = 20
max-diagnostics = 10
#==========================================
# [editor.indent-guides]
# rainbow-indent = "dim"
# WAIT FOR 25.07.1 VERSION
#==========================================
[editor.lsp]
# Active le LSP
enable = true
display-messages = true
display-inlay-hints = true
auto-signature-help = true
#==========================================
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
#==================================================================================
[keys.insert]
C-s = [":write", "normal_mode"]
# Déplace le curseur au début du mot précédent
A-left = "move_prev_word_start"
# Déplace le curseur au début du mot suivant
A-right = "move_next_word_start"
# Bonus : Naviguer d'une ligne à l'autre
A-j = "move_line_down"
A-k = "move_line_up"
A-l = "move_next_word_start"
A-h = "move_prev_word_start"
#==========================================
[keys.normal]
A-f = ":format"
C-r = ":rl"
C-s = ":w"
#==========================================
[keys.normal."+"]
c = ":run-shell-command cargo check"
t = ":run-shell-command cargo test"
b = ":run-shell-command cargo build"
#==========================================
[keys.normal.space]
# La touche 'a' après 'space' exécutera la commande
x = ":run-shell-command cargo clippy --fix --allow-dirty"

#==========================================
[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

